---
title: "Microbial_association_network-area_relationship"
author: "Pandeng Wang"
date: "6/24/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load defined functions
```{r}
source("Defined_functions_for_NAR.R")
```

## Read data
```{r read data}
library(tidyverse)
# read otu table
bac_sampleXotu <- read_tsv("data/2015_TIL_bac_sampleXotu.tsv")

fungi_sampleXotu <- read_tsv("data/2015_TIL_fungi_sampleXotu.tsv")

# read sample metadata
sample_metadata <- read_tsv("data/2015_TIL_sample_metadata.tsv")

plot_metadata <- unique(sample_metadata[,c("plot", "Island", "Island_ID", "area", "logArea")])

# make sure sample orders are same in dfferent data frame
sample_metadata$SampleID == bac_sampleXotu$SampleID
sample_metadata$SampleID == fungi_sampleXotu$SampleID
```

## Figure 1: network size and average degree Vs logArea
```{r figure1}
library(SpiecEasi)
library(cowplot)
# split sampleXotu table into plot level sampleXotu table
# and only keep OTU that occur in all 4 samples in each plot
bac_sampleXotu_plot_f4 <- column_to_rownames(bac_sampleXotu, var = "SampleID") %>%
  split_sampleXotu_plot(plot = sample_metadata$plot, occurNum = 4)

fungi_sampleXotu_plot_f4 <- column_to_rownames(fungi_sampleXotu, var = "SampleID") %>%
  split_sampleXotu_plot(plot = sample_metadata$plot, occurNum = 4)

# construct network for each plot using SPIEC-EASI method
bac_sampleXotu_plot_f4 <- lapply(bac_sampleXotu_plot_f4, as.matrix)

bac_spiec_plot_f4 <- lapply(bac_sampleXotu_plot_f4, spiec.easi, method = "mb", lambda.min.ratio = 3e-1, nlambda=10, pulsar.params = list(rep.num=20))

unlist(lapply(bac_spiec_plot_f4, function(x) sum(getRefit(x))/2))

fungi_sampleXotu_plot_f4 <- lapply(fungi_sampleXotu_plot_f4, as.matrix)

fungi_spiec_plot_f4 <- lapply(fungi_sampleXotu_plot_f4, spiec.easi, method = "mb", lambda.min.ratio = 5e-2, nlambda=10, pulsar.params = list(rep.num=20))

unlist(lapply(fungi_spiec_plot_f4, function(x) sum(getRefit(x))/2))

# convert spiec object to igraph
bac_spiec_plot_f4_igraph <- lapply(bac_spiec_plot_f4, coff_to_igraph, sym_beta = T)

fungi_spiec_plot_f4_igraph <- lapply(fungi_spiec_plot_f4, coff_to_igraph, sym_beta = T)

# remove isolated vertex
bac_spiec_plot_f4_igraph_rmIso <- lapply(bac_spiec_plot_f4_igraph, rm_isolated_vertex)

fungi_spiec_plot_f4_igraph_rmIso <- lapply(fungi_spiec_plot_f4_igraph, rm_isolated_vertex)

# calculate network size and average degree
bac_spiec_plot_f4_igraph_rmIso_2pro <- lapply(bac_spiec_plot_f4_igraph_rmIso, 
                                               cal_net_property)

bac_spiec_plot_f4_igraph_rmIso_2pro <- do.call(rbind, bac_spiec_plot_f4_igraph_rmIso_2pro)

fungi_spiec_plot_f4_igraph_rmIso_2pro <- lapply(fungi_spiec_plot_f4_igraph_rmIso, 
                                               cal_net_property)

fungi_spiec_plot_f4_igraph_rmIso_2pro <- do.call(rbind, fungi_spiec_plot_f4_igraph_rmIso_2pro)

# plot network size and average degree Vs logArea
bac_spiec_plot_df <- bac_spiec_plot_f4_igraph_rmIso_2pro %>%
  rownames_to_column(var = "plot") %>%
  gather(key = "key", value = "value", -plot) %>%
  left_join(plot_metadata, by = "plot") %>%
  mutate(key = as_factor(key))


bac_spiec_plot_2pro_logArea_stat <- bac_spiec_plot_df %>% 
  group_by(key) %>%
  summarise(r2 = (summary(lm(value ~ logArea)))$r.squared,
            r2.adj = (summary(lm(value ~ logArea)))$adj.r.squared,
            p = cor.test(value, logArea)$p.value) %>%
  mutate(taxon = "Bacteria", 
         rlabel = paste("R ^ 2 == ", round(r2,3), sep = ""),
         plabel = paste("italic(P) == ", format(p, 2, scientific = T, digits = 2), sep = ""),
         x = 6.5,
         y = -Inf)


p_bac_spiec_plot_net_rmIso_2pro <- bac_spiec_plot_df %>%
  ggplot(aes(x=logArea, y=value)) +
  geom_point(size=0.5, color = "#E1A970")  +
  geom_smooth(se=T, method = "lm", size=0.5, color = "#E1A970") +
  geom_text(data = bac_spiec_plot_2pro_logArea_stat, 
            aes(x, y, label = rlabel), inherit.aes = F, parse = T, vjust = -2, size = 2) + 
  geom_text(data = bac_spiec_plot_2pro_logArea_stat, 
            aes(x, y, label = plabel), inherit.aes = F, parse = T, vjust = -1.5, size = 2) +
  facet_grid(key ~ taxon, scales = "free_y") +
  theme_bw(base_size = 10) +
  theme(panel.grid = element_blank()) +
  scale_x_continuous(breaks=seq(3, 7, 1)) + 
  ylab("Value") + xlab("log10 Area")



fungi_spiec_plot_df <- fungi_spiec_plot_f4_igraph_rmIso_2pro %>%
  rownames_to_column(var = "plot") %>%
  gather(key = "key", value = "value", -plot) %>%
  left_join(plot_metadata, by = "plot") %>%
  mutate(key = as_factor(key))


fungi_spiec_plot_2pro_logArea_stat <- fungi_spiec_plot_df %>% 
  group_by(key) %>%
  summarise(r2 = (summary(lm(value ~ logArea)))$r.squared,
            r2.adj = (summary(lm(value ~ logArea)))$adj.r.squared,
            p = cor.test(value, logArea)$p.value) %>%
  mutate(taxon = "Fungi", 
         rlabel = paste("R ^ 2 == ", round(r2,3), sep = ""),
         plabel = paste("italic(P) == ", format(p, 2, scientific = T, digits = 2), sep = ""),
         x = 6.5,
         y = -Inf)

p_fungi_spiec_net_rmIso_2pro <- fungi_spiec_plot_df %>%
  ggplot(aes(x=logArea, y=value)) +
  geom_point(size=0.5, color = "#29ABE2")  +
  geom_smooth(se=T, method = "lm", size=0.5, color = "#29ABE2") +
  geom_text(data = fungi_spiec_plot_2pro_logArea_stat, 
            aes(x, y, label = rlabel), inherit.aes = F, parse = T, vjust = -2, size = 2) + 
  geom_text(data = fungi_spiec_plot_2pro_logArea_stat, 
            aes(x, y, label = plabel), inherit.aes = F, parse = T, vjust = -1.5, size = 2) +
  facet_grid(key ~ taxon, scales = "free_y") +
  theme_bw(base_size = 10) +
  theme(panel.grid = element_blank()) +
  scale_x_continuous(breaks=seq(3, 7, 1)) + 
  ylab("") + xlab("log10 Area")

# combine bac and fungi
plot_grid(p_bac_spiec_plot_net_rmIso_2pro, p_fungi_spiec_net_rmIso_2pro, ncol = 2)

ggsave(filename = "Fig1_network_2pro_logArea.pdf", height = 80, width = 120, units = "mm")
```

## Figure 2: SEM
```{r figure2} 
library(piecewiseSEM)
library(corrplot)
library(psych)

# mean alpha diversity and beta diversity in each plot
bac_sampleXotu_plot <- column_to_rownames(bac_sampleXotu, var = "SampleID") %>%
  split_sampleXotu_plot(plot = sample_metadata$plot)

bac_plot_alpha_beta <- lapply(bac_sampleXotu_plot, cal_plot_alpha_beta_mean)

bac_plot_alpha_beta_df <- bind_rows(bac_plot_alpha_beta, .id = "plot") %>%
  left_join(plot_metadata, by = "plot") %>%
  mutate(taxon = "Bacteria", key = as_factor(as.character(key)))


fungi_sampleXotu_plot <- column_to_rownames(fungi_sampleXotu, var = "SampleID") %>%
  split_sampleXotu_plot(plot = sample_metadata$plot)

fungi_plot_alpha_beta <- lapply(fungi_sampleXotu_plot, cal_plot_alpha_beta_mean)

fungi_plot_alpha_beta_df <- bind_rows(fungi_plot_alpha_beta, .id = "plot") %>%
  left_join(plot_metadata, by = "plot") %>%
  mutate(taxon = "Fungi", key = as_factor(as.character(key)))

# explore soil properties
soil9 <- column_to_rownames(sample_metadata, var = "SampleID") %>% 
  select(pH:moisture, Aal, Aca, Amg)
pairs.panels(soil9)
# log transform AP, Aca, Amg to approach normal distribution
soil9$logAP <- log1p(soil9$AP)
soil9$logAca <- log1p(soil9$Aca)
soil9$logAmg <- log1p(soil9$Amg)
pairs.panels(soil9)

soil9_stan <- as.data.frame(scale(soil9)) %>%
  select(-AP, -Amg, -Aca)

pairs.panels(soil9_stan)

corrplot.mixed(cor(soil9_stan), upper = "ellipse", lower = "number")

soil9_stan_plot <- apply(soil9_stan, 2, function(x) tapply(x, sample_metadata$plot, mean))

cor(soil9_stan_plot, plot_metadata$logArea)

# select three soil properties that have significantly 
# positive relationship with island area
soil3_stan_plot <- soil9_stan_plot %>%
  as.data.frame() %>%
  rownames_to_column(var = "plot") %>%
  select(plot, moisture, TOC, TN)

# split sampltXsoil table 
sampleXsoil_plot <- split_sampleXsoil_plot(soil9_stan, plot = sample_metadata$plot)

# use all soil properties to calculate soil heterogeneity of each plot
soil_euc_plot <- lapply(sampleXsoil_plot, function(x) data.frame(euc = mean(dist(x))))
soil_euc_plot <- bind_rows(soil_euc_plot, .id = "plot") %>%
  left_join(plot_metadata, by = "plot")

# SEM
# ---- bac ----
bac_sem_df <- bac_plot_alpha_beta_df %>%
  select(-sd) %>%
  spread(key = key, value = mean) %>%
  left_join(soil3_stan_plot, by = "plot") %>%
  left_join(soil_euc_plot[,c("plot", "euc")], by = "plot") %>%
  left_join(rownames_to_column(bac_spiec_plot_f4_igraph_rmIso_2pro, var = "plot"),
            by = "plot")
  

bac_sem_mod <- psem(
  lm(TOC ~ logArea, data = bac_sem_df),
  lm(moisture ~ logArea, data = bac_sem_df),
  lm(TN ~ logArea, data = bac_sem_df),
  lm(euc ~ logArea, data = bac_sem_df),
  lm(OTUnum ~ TOC + moisture + TN, data = bac_sem_df),
  lm(Jaccard ~ euc, data = bac_sem_df),
  lm(average_degree ~ TOC + moisture + TN + OTUnum + Jaccard, data = bac_sem_df),
  lm(network_size ~ OTUnum + Jaccard, data = bac_sem_df)
)

summary(bac_sem_mod)

bac_sem_mod2 <- psem(
  lm(moisture ~ logArea, data = bac_sem_df),
  lm(OTUnum ~ logArea + moisture, data = bac_sem_df),
  lm(average_degree ~ OTUnum + Jaccard, data = bac_sem_df),
  lm(network_size ~ logArea + OTUnum + Jaccard, data = bac_sem_df)
  
)

summary(bac_sem_mod2)

# ---- fungi ----
fungi_sem_df <- fungi_plot_alpha_beta_df %>%
  select(-sd) %>%
  spread(key = key, value = mean) %>%
  left_join(soil3_stan_plot, by = "plot") %>%
  left_join(soil_euc_plot[,c("plot", "euc")], by = "plot") %>%
  left_join(rownames_to_column(fungi_spiec_plot_f4_igraph_rmIso_2pro, var = "plot"),
            by = "plot")

fungi_sem_mod <- psem(
  lm(TOC ~ logArea, data = fungi_sem_df),
  lm(moisture ~ logArea, data = fungi_sem_df),
  lm(TN ~ logArea, data = fungi_sem_df),
  lm(euc ~ logArea, data = fungi_sem_df),
  lm(OTUnum ~ TOC + moisture + TN, data = fungi_sem_df),
  lm(Jaccard ~ euc, data = fungi_sem_df),
  lm(average_degree ~ TOC + moisture + TN + OTUnum + Jaccard, data = fungi_sem_df),
  lm(network_size ~ OTUnum + Jaccard, data = fungi_sem_df)
)

summary(fungi_sem_mod)

fungi_sem_mod2 <- psem(
  lm(Jaccard ~ logArea, data = fungi_sem_df),
  lm(average_degree ~ OTUnum + Jaccard, data = fungi_sem_df),
  lm(network_size ~  OTUnum + Jaccard, data = fungi_sem_df)
)

summary(fungi_sem_mod2)
```

## Figure S1: spearman correlation network
```{r}
# construct network
bac_spear_plot_f4 <- lapply(bac_sampleXotu_plot_f4, cal_rp_from_sampleXotu)

fungi_spear_plot_f4 <- lapply(fungi_sampleXotu_plot_f4, cal_rp_from_sampleXotu)

# calculate network properties using different coefficient thresholds
bac_spear_plot_net_2pro <- cal_spearNet_property_use_diffthreshold(bac_spear_plot_f4)

bac_spear_plot_df <- bac_spear_plot_net_2pro %>%
  left_join(plot_metadata[,c("plot", "logArea")], by = "plot")

fungi_spear_plot_net_2pro <- cal_spearNet_property_use_diffthreshold(fungi_spear_plot_f4)

fungi_spear_plot_df <- fungi_spear_plot_net_2pro %>%
  left_join(plot_metadata[,c("plot", "logArea")], by = "plot")

# plot net 2pro Vs logArea
bac_spear_plot_df_stat <- bac_spear_plot_df %>% group_by(key, r) %>%
  summarise(r2 = (summary(lm(value ~ logArea)))$r.squared,
            r2.adj = (summary(lm(value ~ logArea)))$adj.r.squared,
            p = cor.test(value, logArea)$p.value) %>%
  mutate(taxon = "Bacteria", 
         rlabel = paste("R ^ 2 == ", round(r2,3), sep = ""),
         plabel = paste("italic(P) == ", format(p, 2, scientific = T, digits = 2), sep = ""),
         x = 6.5,
         y = -Inf)

p_bac_spear_plot <- bac_spear_plot_df %>%
  ggplot(aes(x=logArea, y=value)) +
  geom_point(size=0.5, color = "#E1A970")  +
  geom_smooth(se=T, method = "lm", size=0.5, color = "#E1A970") +
  geom_text(data = bac_spear_plot_df_stat, 
            aes(x, y, label = rlabel), inherit.aes = F, parse = T, vjust = -2, size = 2) + 
  geom_text(data = bac_spear_plot_df_stat, 
            aes(x, y, label = plabel), inherit.aes = F, parse = T, vjust = -1.5, size = 2) +
  facet_grid(key ~ r, scales = "free") +
  theme_bw(base_size = 10) +
  theme(panel.grid = element_blank()) +
  scale_x_continuous(breaks=seq(3, 7, 1)) + 
  ylab("Value") + xlab("")


fungi_spear_plot_df_stat <- fungi_spear_plot_df %>% group_by(key, r) %>%
  summarise(r2 = (summary(lm(value ~ logArea)))$r.squared,
            r2.adj = (summary(lm(value ~ logArea)))$adj.r.squared,
            p = cor.test(value, logArea)$p.value) %>%
  mutate(taxon = "Fungi", 
         rlabel = paste("R ^ 2 == ", round(r2,3), sep = ""),
         plabel = paste("italic(P) == ", format(p, 2, scientific = T, digits = 2), sep = ""),
         x = 6.5,
         y = -Inf)

p_fungi_spear_plot <- fungi_spear_plot_df %>%
  ggplot(aes(x=logArea, y=value)) +
  geom_point(size=0.5, color = "#29ABE2")  +
  geom_smooth(se=T, method = "lm", size=0.5, color = "#29ABE2") +
  geom_text(data = fungi_spear_plot_df_stat, 
            aes(x, y, label = rlabel), inherit.aes = F, parse = T, vjust = -2, size = 2) + 
  geom_text(data = fungi_spear_plot_df_stat, 
            aes(x, y, label = plabel), inherit.aes = F, parse = T, vjust = -1.5, size = 2) +
  facet_grid(key ~ r, scales = "free") +
  theme_bw(base_size = 10) +
  theme(panel.grid = element_blank()) +
  scale_x_continuous(breaks=seq(3, 7, 1)) + 
  ylab("Value") + xlab("log10 Area")

# combine bac and fungi
plot_grid(p_bac_spear_plot, p_fungi_spear_plot, nrow = 2)

ggsave(filename = "FigS1_network_2pro_logArea.pdf", height = 160, width = 180, units = "mm")
```

## Figure S2: SparCC network
```{r}
library(SpiecEasi)
# calculate sparcc correlation
bac_sparcc_plot_f4 <- lapply(bac_sampleXotu_plot_f4, sparcc)

fungi_sparcc_plot_f4<- lapply(fungi_sampleXotu_plot_f4, sparcc)

# calculate sparcc p in linux server, this step is very time-consuming
save(bac_sampleXotu_plot_f4, fungi_sampleXotu_plot_f4, cal_p_for_sparcc, file = "cal_p_for_sparcc.RData")

#~~~~~~~~~~~~~~~~~~~~~~
#!/usr/bin/env Rscript
load("cal_p_for_sparcc.RData")
bac_sparcc_plot_f4_p <- lapply(bac_sampleXotu_plot_f4, cal_p_for_sparcc, times = 999, cores = 50)
save(bac_sparcc_plot_f4_p, file = "bac_sparcc_plot_f4_p.RData")

fungi_sparcc_plot_f4_p <- lapply(fungi_sampleXotu_plot_f4, cal_p_for_sparcc, times = 999, cores = 50)
save(fungi_sparcc_plot_f4_p, file = "fungi_sparcc_plot_f4_p.RData")
#~~~~~~~~~~~~~~~~~~~~~~


load("bac_sparcc_plot_f4_p.RData")
load("fungi_sparcc_plot_f4_p.RData")

for(i in names(bac_sparcc_plot_f4_p)){
  bac_sparcc_plot_f4[[i]]$p <- bac_sparcc_plot_f4_p[[i]]
}

for(i in names(fungi_sparcc_plot_f4_p)){
  fungi_sparcc_plot_f4[[i]]$p <- fungi_sparcc_plot_f4_p[[i]]
}

# calculate sparcc networks' properties using different thresholds
bac_sparcc_plot_net_2pro <- cal_sparccNet_property_use_diffthreshold(bac_sparcc_plot_f4)

fungi_sparcc_plot_net_2pro <- cal_sparccNet_property_use_diffthreshold(fungi_sparcc_plot_f4)


# plot 
bac_sparcc_plot_df <- bac_sparcc_plot_net_2pro %>%
  left_join(plot_metadata[,c("plot", "logArea")], by = "plot")

bac_sparcc_plot_df_stat <- bac_sparcc_plot_df %>% group_by(key, r) %>%
  summarise(r2 = (summary(lm(value ~ logArea)))$r.squared,
            r2.adj = (summary(lm(value ~ logArea)))$adj.r.squared,
            p = cor.test(value, logArea)$p.value) %>%
  mutate(taxon = "Bacteria", 
         rlabel = paste("R ^ 2 == ", round(r2,3), sep = ""),
         plabel = paste("italic(P) == ", format(p, 2, scientific = T, digits = 2), sep = ""),
         x = 6.5,
         y = -Inf)

p_bac_sparcc_plot <- bac_sparcc_plot_df %>%
  ggplot(aes(x=logArea, y=value)) +
  geom_point(size=0.5, color = "#E1A970")  +
  geom_smooth(se=T, method = "lm", size=0.5, color = "#E1A970") +
  geom_text(data = bac_sparcc_plot_df_stat, 
            aes(x, y, label = rlabel), inherit.aes = F, parse = T, vjust = -2, size = 2) + 
  geom_text(data = bac_sparcc_plot_df_stat, 
            aes(x, y, label = plabel), inherit.aes = F, parse = T, vjust = -1.5, size = 2) +
  facet_grid(key ~ r, scales = "free") +
  theme_bw(base_size = 10) +
  theme(panel.grid = element_blank()) +
  scale_x_continuous(breaks=seq(3, 7, 1)) + 
  ylab("Values") + xlab("")


fungi_sparcc_plot_df <- fungi_sparcc_plot_net_2pro %>%
  left_join(plot_info[,c("plot", "logArea")], by = "plot")

fungi_sparcc_plot_df_stat <- fungi_sparcc_plot_df %>% group_by(key, r) %>%
  summarise(r2 = (summary(lm(value ~ logArea)))$r.squared,
            r2.adj = (summary(lm(value ~ logArea)))$adj.r.squared,
            p = cor.test(value, logArea)$p.value) %>%
  mutate(taxon = "Fungi", 
         rlabel = paste("R ^ 2 == ", round(r2,3), sep = ""),
         plabel = paste("italic(P) == ", format(p, 2, scientific = T, digits = 2), sep = ""),
         x = 6.5,
         y = -Inf)

p_fungi_sparcc_plot <- fungi_sparcc_plot_df %>%
  ggplot(aes(x=logArea, y=value)) +
  geom_point(size=0.5, color = "#29ABE2")  +
  geom_smooth(se=T, method = "lm", size=0.5, color = "#29ABE2") +
  geom_text(data = fungi_sparcc_plot_df_stat, 
            aes(x, y, label = rlabel), inherit.aes = F, parse = T, vjust = -2, size = 2) + 
  geom_text(data = fungi_sparcc_plot_df_stat, 
            aes(x, y, label = plabel), inherit.aes = F, parse = T, vjust = -1.5, size = 2) +
  facet_grid(key ~ r, scales = "free") +
  theme_bw(base_size = 10) +
  theme(panel.grid = element_blank()) +
  scale_x_continuous(breaks=seq(3, 7, 1)) + 
  ylab("Value")

# combine bac and fungi
plot_grid(p_bac_sparcc_plot, p_fungi_sparcc_plot, nrow = 2)

ggsave(filename = "FigS2_sparcc_network_2pro_logArea.pdf", height = 160, width = 180, units = "mm")
```


